site_name: Wave
repo_url: https://github.com/Jumpercables/Wave/
site_author: Kyle Baesler
markdown_extensions:
    - smarty
    - admonition
    - footnotes
theme: material
pages:
- Getting Started:
  - Overview: index.md
  - Samples: samples.md
- Features: features.md
- Frequently Asked Questions: faq.md
- About:
  - Contributing: contribute.md
  - Release Notes: release-notes.md
